#!/bin/bash -e
dir=nacl-20110221
buildname=`hostname | sed 's/\..*//' | tr -cd '[a-z][A-Z][0-9]'`

if [ ! -e $dir.tar.bz2 ]
then
  echo 'Downloading...'
  wget http://hyperelliptic.org/nacl/$dir.tar.bz2
fi

if [ ! -e $dir ]
then
  echo 'Unpacking...'
  tar xaf $dir.tar.bz2
fi

if [ ! -e $dir/build/$buildname ]
then
  cd $dir
  echo 'Building... (no output will be shown, and it will take a while; please be patient)'
  "./do"
  cd ..
fi

if [ ! -e nacl ]
then
  ln -s $dir/build/$buildname nacl
fi

